### ISSUE TITLE
WymEditor / Safari

### ISSUE THREAD

**Issue by ccordenier** [spreadthesource/wooki#11]
WymEditor makes Safari totally crash, truly cannot figure out why at the moment ?

**Comment by robink** [comment]
Can you explain how to reproduce that crash?
I may try on my environment

**Comment by ccordenier** [comment]
Edit book abstract, publish, edit again, and ....

**Comment by ccordenier** [comment]
It seems like there is bad interaction between $('data').activate() and wymeditor creation.
Since we find a better solution, i have disabled tapestry form autofocus feature.
