### ISSUE TITLE
Add authors to the generated HTML

### ISSUE THREAD

**Issue by gounthar** [spreadthesource/wooki#30]
We'll need to know the authors to produce PDF or other formats (they should at least appear on the cover).
We have to find a way to put them in the DOM, maybe:
http://www.w3.org/TR/html401/struct/global.html#h-7.4.4
We should have a look at the "Publisher" meta tag too...

**Comment by robink** [comment]
What about this one?
http://www.w3.org/TR/html5/history.html#link-type-author

**Comment by gounthar** [comment]
Why not? Don't wanna be "author"itative. :-P
&lt;LINK REV=MADE TITLE="Sarah Schoenfeld" HREF="mailto:sarah@whatever.idocs.com"&gt;

There was a time where we used to play with Dublin Core for such needs:
http://www.w3.org/MarkUp/2009/rdfa-for-html-authors

**Comment by gounthar** [comment]
Done
