### ISSUE TITLE
Use of external image

### ISSUE THREAD

**Issue by gounthar** [spreadthesource/wooki#32]
You can use external images in your book, but that could lead to a problem when rendering with FOP. 
I'll have to find how to link FOP to commons-http-client...

**Comment by robink** [comment]
As we also don't know how to handle them in the web view (are we going to use only external images, how are we going to show them?), I propose to forget this feature for wooki 0.1, as we need to evaluate how to handle images in global way.

What do you think?

**Comment by gounthar** [comment]
Christophe proposed to make them available through the filesystem, and to store them locally, or even in a database (hope I didn't misrepresent your thought, Christophe).
It would be easier to content ourselves with images linked to the website...
