### ISSUE TITLE
Centralize charset encoding configuration

### ISSUE THREAD

**Issue by robink** [spreadthesource/wooki#36]
As I was editing some class, I found hard coded reference to a specific charset (UTF-8).
We should centralize the charset choice in the AppModule for example, to allow use of another charset.

**Comment by ccordenier** [comment]
As discussed, the question is do we have to use byte arrays for publication content ?

**Comment by robink** [comment]
I guess we should find a cleaner way to do that.

**Comment by ccordenier** [comment]
Done and commited, now Spring are using the same encoding configuration as Tapestry5
