### ISSUE TITLE
Redirect to dashboard after signup and display a kindly message on how to start creating book

### ISSUE THREAD

**Issue by ccordenier** [spreadthesource/wooki#45]

**Comment by robink** [comment]
+1

As we know the product since the beginning, we are starting to forgot to "guide" the user through the application.

The issue you just open could be applied for a lot of similar navigation workflow.

**Comment by ccordenier** [comment]
Done and committed for signup process. For other navigation process, we will create new issues or a more general one that can be addressed for each case.
