### ISSUE TITLE
Capcha validation

### ISSUE THREAD

**Issue by badluck13** [spreadthesource/wooki#61]
Hi, this is my first issue created here, I hope that I can help, at least with good ideas.

First of them is Captcha validation, this should be used only on register page so users won't be annoyed to much :)

And best captcha that I seen is this, it helps digitize textual documents so this would be useful in many ways :)

http://recaptcha.net/

**Comment by robink** [comment]
Hi !

Thanx for your feedback. In fact, captcha was one of the top priority feature we wanted to implement for the next version of Wooki. The issue your are pointing out was implicit in issue 39 "Add anti-spam logic on sigin and signup".

Recaptcha seems very good yes, I think we will try this solution.

**Comment by badluck13** [comment]
Sorry for duplicate issue :( 

I'm also a tapestry developer and I love tapestry and I really appreciate what you ppl are doing.

And I will help you as much as I can. :)

**Comment by robink** [comment]
Cool, we looking forward for fork/patch/pull request ! :)

**Comment by badluck13** [comment]
As soon I get some time to spend with you on coding :)

By the way, I'm looking for open source project to participate as a part for my specialization thesis on faculty, so if I can keep with you I would love to work with you  on wooki :)

**Comment by ccordenier** [comment]
See http://code.google.com/p/recaptcha/downloads/list?q=label:java-Latest
Maybe we can combine this with the implementation of Kaptcha suggested by Howard at http://tapestryjava.blogspot.com/search/label/captcha

And then let people who have download wooki to choose between an embedded captcha  solution (default) or the reCaptcha solution. 

We must keep in mind that wooki has also been designed for Tapestry 5 user so they can run 'mvn jetty:run' and see a full running application :)

**Comment by ccordenier** [comment]
Postponed to 0.3 for priority reasons

**Comment by ccordenier** [comment]
Implemented with Howard's tapx captcha.
