### ISSUE TITLE
Error in XHTMLToFormattingObjects

### ISSUE THREAD

**Issue by badluck13** [spreadthesource/wooki#62]
eclipse is getting error on your wooki project and I can't get what is wrong, probably because I use windows :(

Error place is XHTMLToFormattingObjects.java

on line 30: import javax.annotation.PostConstruct;

error description
Access restriction: The type PostConstruct is not accessible due to restriction on required library C:\Program Files\Java\jre6\lib\rt.jar

I use windows vista, and eclipse Galileo.

**Comment by robink** [comment]
It is not really a bug. 
Just go to your eclipse preferences, check Java / Errors and lower error level (simply apply warning) on restrictions access.

**Comment by badluck13** [comment]
Ok, this fixed everything... tnx :)

**Comment by robink** [comment]
solved.
