### ISSUE TITLE
Securing user creations

### ISSUE THREAD

**Issue by gounthar** [spreadthesource/wooki#9]
We can create new users with passwords equal to login. No security check seems to be implemented. We maybe could use http://static.springsource.org/spring-security/site/features.html ?

**Comment by ccordenier** [comment]
I totally agree. Currently i use a tapestry-spring-security implementation for user authentication and password encryption. But applying security policies to password is also a good and important thing

**Comment by robink** [comment]
I agree for some light rules like:
- min 6 chars
- password != username
  Theses must be there.

But I'm clearly against hardcore passwords restrictions. I find that far more usable to let the user choose the password he wants. And we wants usability for Wooki.

The following reading is a great proof of the non-sense of forcing high characters complexity in passwords. There is a lot of others ways to secure a web application.
http://www.baekdal.com/articles/usability/password-security-usability/

**Comment by ccordenier** [comment]
Ok, done and committed. This two constraints will be sufficient at the moment.
