### ISSUE TITLE
Accentuation problems in content of a chapter

### ISSUE THREAD

**Issue by gbm-bailleul** [spreadthesource/wooki#90]
French accuentued characters are replaced by "??" in the body of a chapter. This problem does not exists with the title of the chapter where the value is not tampered.
When an edit is intented on the body of the chapter all accentued characters are modified.

 I think the encoding of the textarea is forced in a bad default value during the save stage.

**Comment by robink** [comment]
Thanx for the feedback, added as a priority for 0.2 release.

**Comment by ccordenier** [comment]
Wooki has been designed to use UTF-8, so to solve your problem add this JAVA Option to your application server init script : -Dfile.encoding=UTF-8, it should solve the problem.

**Comment by ccordenier** [comment]
Wierd, cannot reproduce the problem on my mac book ... I continue to investigate

**Comment by ccordenier** [comment]
Fixed : now works both on ubuntu and mac (and windows i guess :)

**Comment by ccordenier** [comment]
Commited
