### ISSUE TITLE
Editing chapter

### ISSUE THREAD

**Issue by abangkis** [spreadthesource/wooki#91]
Hi, I'm having trouble editing the title and content of a chapter. Maybe you can give a more simple way like an edit link from the working copy page ? Anyway its awsome, keep up the good work. Can't wait for the next release

**Comment by robink** [comment]
Our links for editing or settings pages are not good from an usability point of view.

We are thinking of an UI more like Github, with buttons instead of simple links.

The idea or providing shortcuts from other entry point is good, we will keep that in mind.

**Comment by abangkis** [comment]
Hi, a little more feed back. I usually create the structure of things i want to write. So instead of add a chapter and go directly to the chapter. Maybe wooki could stay on the main page until i added all of the chapter for my book instead of going directly to the chapter.

**Comment by ccordenier** [comment]
Done !
