### ISSUE TITLE
Some concept on working copy

### ISSUE THREAD

**Issue by abangkis** [spreadthesource/wooki#92]
Hi, maybe you can add a page to give brief explanation of working copy and publish concept in wooki. I think when the project grow bigger the concept could give some confusion for new user

**Comment by robink** [comment]
Yes! (again, you are totally right)

We noticed on our demo website that every one knows how to :
- signup
- login
- create a book

That's it.
Everybody stop when they have to create a chapter and edit the content. We are thinking about multiples solutions, like providing :
- a Tour page, which will introduce Wooki
- a video demonstration on the main page
- contextual help on different pages, like flash messages which will appear only once.

**Comment by robink** [comment]
And of course, providing a better UI. :)

**Comment by ccordenier** [comment]
Now we use 'Draft' instead of 'Working copy', should be clearer
