### ISSUE TITLE
Exporting PDF in 0.1

### ISSUE THREAD

**Issue by abangkis** [spreadthesource/wooki#94]
Hi I'm having a problem when exporting my book to pdf. I have an Abstract and a chapter publish. But when ever i export to pdf. The pdf file is 0 kb in size and contains nothing.

**Comment by robink** [comment]
Yes, this bug used to happen randomly, that's why we are switching to flyingsaucer in 0.2 for PDF generation.

**Comment by robink** [comment]
By the way, I m sorry but as we are not using this PDF generation method anymore, I think that we are not going to correct this release. :(

**Comment by abangkis** [comment]
That's okay. I just wait for 0.2. Is there a date release ? I try checking out the code from github. But there's some library issue. Since I'm not very fond of maven. I'll try fixing it some other time. Keep up the great job guys :D

**Comment by ccordenier** [comment]
Should be solved now

**Comment by abangkis** [comment]
Okay, thanks a lot :D
